name = "fortran-s3-accessor"
version = "1.0.1"
license = "MIT"
author = "Paul Gierz"
maintainer = "pgierz@awi.de"
copyright = "Copyright 2025, Paul Gierz"
homepage = "https://github.com/pgierz/fortran-s3-accessor"
description = "Simple Fortran library for S3-compatible object storage access"
categories = ["io", "cloud", "scientific-computing"]
keywords = ["s3", "object-storage", "netcdf", "climate", "hpc"]
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"


[dev-dependencies]
test-drive = { git = "https://github.com/fortran-lang/test-drive", tag = "v0.4.0" }

