name = "s3-netcdf-example"
version = "0.1.0"
license = "license"
author = "Paul Gierz"
maintainer = "pgierz@awi.de"
copyright = "Copyright 2025, Paul Gierz"
[dependencies]
fortran-s3-accessor = { path = "../.." }
netcdf-interfaces = { git = "https://github.com/LKedward/netcdf-interfaces.git" }


[[executable]]
name = "s3_netcdf_example"
source-dir = "."
main = "s3_netcdf_example.f90"
