s3_init – fortran-s3-accessor
s3_init Subroutine
5 statements
Source File
public subroutine s3_init(config)
Initialize the S3 HTTP module with configuration.
This subroutine must be called before any S3 operations can be performed. It stores the provided configuration for use by all subsequent operations.
@param[in] config S3 configuration containing bucket, endpoint, and credentials
Example
type(s3_config) :: config
config%bucket = 'my-bucket'
config%region = 'us-east-1'
config%use_https = .true.
call s3_init(config)
Arguments
Type Intent Optional Attributes Name
type(s3_config), intent(in) :: config
Called by
Source Code
    subroutine s3_init(config)
        type(s3_config), intent(in) :: config
        current_config = config
        initialized = .true.
    end subroutine s3_init
Call graph
s3_delete_uri calls s3_init
s3_exists_uri calls s3_init
s3_get_uri calls s3_init
s3_put_uri calls s3_init